# Generated by Django 5.2.17 on 2026-09-14 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                ("external_id", models.CharField(max_length=255)),
                (
                    "title_id",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9A-Fa-f]{16}\\Z",
                                "Enter exactly 16 hexadecimal digits.",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("product_code", models.CharField(blank=True, max_length=64)),
                ("region", models.CharField(blank=True, max_length=64)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "catalog entries",
                "ordering": ("source", "external_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="unique_catalog_entry_source_external_id",
                    )
                ],
            },
        ),
    ]
